In [2]:
import pandas as pd

data = pd.read_csv("Priem.csv")
data

,Пол,Сумма.баллов,ЕГЭ...матем.,ЕГЭ...рус.яз.,Аттестат.с.отличием.оценка,ГТО.оценка,Сочинение.оценка,Регион,Тип.насел..пункта,Дата.рождения,День.рождения,Месяц.рождения
0,МУЖСКОЙ,388,90.0,98.0,5,0,1,Красноярский край,ГОРОД,24.09.1998,24,9
1,ЖЕНСКИЙ,351,84.0,87.0,0,0,2,Чувашская Респ,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,14.02.1997,14,2
2,ЖЕНСКИЙ,355,94.0,91.0,5,0,2,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,25.03.2000,25,3
3,ЖЕНСКИЙ,338,76.0,88.0,5,0,2,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,19.11.1999,19,11
4,МУЖСКОЙ,349,82.0,93.0,5,0,2,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,12.12.1999,12,12
...,...,...,...,...,...,...,...,...,...,...,...,...
1385,МУЖСКОЙ,396,100.0,98.0,0,0,2,Челябинская обл,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,17.07.1999,17,7
1386,ЖЕНСКИЙ,291,92.0,93.0,5,0,2,Хабаровский край,ГОРОД,27.07.1999,27,7
1387,МУЖСКОЙ,397,100.0,93.0,5,0,1,Дагестан Респ,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,30.08.1999,30,8
1388,ЖЕНСКИЙ,325,76.0,98.0,5,2,2,Свердловская обл,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,17.11.1999,17,11
1389,МУЖСКОЙ,404,100.0,96.0,5,0,3,Челябинская обл,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,28.02.2000,28,2

1) Начнем с простого:
    1. вывести число строк и число столбцов датасета,
    2. вывести название третьего столбца,
    3. вывести пятую строку,
    4. вывести первые 5 строк,
    5. вывести балл ЕГЭ по математике у седьмого абитуриента,
    6. cоздать новый датасет, содержащий только абитуриентов с баллом ЕГЭ по математике больше 98.

In [3]:
print("Число строк и столбцов: ")
print(data.shape[0])
print(data.shape[1])

print("\nНазвание третьего столбца: ")
print(list(data.columns.values)[2])

print("\nПятая строчку: ")
print(data.iloc[[4]])

print("\nПервые пять строк: ")
print(data.iloc[0:5]) ##head - ?

print("\nБалл ЕГЭ: ")
print(data.iloc[6, 2])

ndata = data[data['ЕГЭ...матем.'] > 98]
ndata

Число строк и столбцов:
1390
12

Название третьего столбца:
ЕГЭ...матем.

Пятая строчку:
       Пол  Сумма.баллов  ЕГЭ...матем.  ЕГЭ...рус.яз.  \
4  МУЖСКОЙ           349          82.0           93.0

   Аттестат.с.отличием.оценка  ГТО.оценка  Сочинение.оценка    Регион  \
4                           5           0                 2  Москва г

             Тип.насел..пункта Дата.рождения  День.рождения  Месяц.рождения
4  ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ    12.12.1999             12              12

Первые пять строк:
       Пол  Сумма.баллов  ЕГЭ...матем.  ЕГЭ...рус.яз.  \
0  МУЖСКОЙ           388          90.0           98.0
1  ЖЕНСКИЙ           351          84.0           87.0
2  ЖЕНСКИЙ           355          94.0           91.0
3  ЖЕНСКИЙ           338          76.0           88.0
4  МУЖСКОЙ           349          82.0           93.0

   Аттестат.с.отличием.оценка  ГТО.оценка  Сочинение.оценка  \
0                           5           0                 1
1                           0           0                 2
2                           5           0                 2
3                           5           0                 2
4                           5           0                 2

              Регион            Тип.насел..пункта Дата.рождения  \
0  Красноярский край                        ГОРОД    24.09.1998
1     Чувашская Респ     ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ    14.02.1997
2           Москва г  ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ    25.03.2000
3           Москва г  ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ    19.11.1999
4           Москва г  ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ    12.12.1999

   День.рождения  Месяц.рождения
0             24               9
1             14               2
2             25               3
3             19              11
4             12              12

Балл ЕГЭ:
90.0

,Пол,Сумма.баллов,ЕГЭ...матем.,ЕГЭ...рус.яз.,Аттестат.с.отличием.оценка,ГТО.оценка,Сочинение.оценка,Регион,Тип.насел..пункта,Дата.рождения,День.рождения,Месяц.рождения
20,МУЖСКОЙ,375,100.0,93.0,5,0,2,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,05.08.1999,5,8
30,МУЖСКОЙ,386,99.0,86.0,0,0,1,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,30.05.2000,30,5
36,МУЖСКОЙ,357,99.0,91.0,0,0,2,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,21.12.1999,21,12
37,МУЖСКОЙ,393,100.0,96.0,0,0,1,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,15.02.2000,15,2
40,МУЖСКОЙ,393,100.0,93.0,0,0,2,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,23.08.1999,23,8
...,...,...,...,...,...,...,...,...,...,...,...,...
1279,МУЖСКОЙ,384,100.0,83.0,5,0,2,Приморский край,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,22.06.1999,22,6
1330,ЖЕНСКИЙ,395,100.0,88.0,5,0,2,Забайкальский край,НАСЕЛЕННЫЙ ПУНКТ СЕЛЬСКОГО ТИПА,29.01.2000,29,1
1385,МУЖСКОЙ,396,100.0,98.0,0,0,2,Челябинская обл,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,17.07.1999,17,7
1387,МУЖСКОЙ,397,100.0,93.0,5,0,1,Дагестан Респ,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,30.08.1999,30,8
1389,МУЖСКОЙ,404,100.0,96.0,5,0,3,Челябинская обл,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,28.02.2000,28,2

2. Потренируемся применять loc, assign, apply в Python или apply в R:
    1. вывести строки с седьмой по двадцатую,
    2. вывести только баллы ЕГЭ по русскому и математике для первых 20 человек,
    3. добавить к датасету столбец, в котором стоит "да" , если балл ЕГЭ по математике больше балла
    по русскому и "нет" иначе (можно true, false),
    4. создать новый датасет, содержащий только абитуриентов со средним баллом больше 95.

In [4]:
data = pd.read_csv("Priem.csv")
data.iloc[6:20]

,Пол,Сумма.баллов,ЕГЭ...матем.,ЕГЭ...рус.яз.,Аттестат.с.отличием.оценка,ГТО.оценка,Сочинение.оценка,Регион,Тип.насел..пункта,Дата.рождения,День.рождения,Месяц.рождения
6,МУЖСКОЙ,383,90.0,98.0,5,0,1,Владимирская обл,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,23.12.1998,23,12
7,ЖЕНСКИЙ,364,80.0,86.0,0,0,2,Санкт-Петербург г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,22.12.1998,22,12
8,МУЖСКОЙ,368,84.0,93.0,0,0,2,Владимирская обл,ГОРОД,13.06.1999,13,6
9,ЖЕНСКИЙ,373,86.0,83.0,5,0,3,Иркутская обл,ГОРОД,23.04.1999,23,4
10,ЖЕНСКИЙ,399,96.0,100.0,5,0,2,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,13.11.1999,13,11
11,МУЖСКОЙ,359,86.0,91.0,0,0,0,Ханты-Мансийский АО,ГОРОД,21.05.1999,21,5
12,ЖЕНСКИЙ,364,86.0,86.0,0,0,0,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,24.08.1999,24,8
13,МУЖСКОЙ,363,96.0,72.0,0,0,1,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,30.07.1999,30,7
14,ЖЕНСКИЙ,376,96.0,93.0,0,0,2,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,11.04.2000,11,4
15,ЖЕНСКИЙ,373,98.0,83.0,5,0,2,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,07.05.2000,7,5
16,МУЖСКОЙ,388,96.0,98.0,0,0,0,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,15.02.2000,15,2
17,ЖЕНСКИЙ,335,90.0,96.0,0,0,2,Московская обл,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,12.06.1999,12,6
18,МУЖСКОЙ,378,90.0,91.0,0,0,1,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,31.01.2000,31,1
19,ЖЕНСКИЙ,364,94.0,100.0,5,0,3,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,10.04.1999,10,4

In [5]:
data.iloc[6:20, 2:4]

    ЕГЭ...матем.  ЕГЭ...рус.яз.
6           90.0           98.0
7           80.0           86.0
8           84.0           93.0
9           86.0           83.0
10          96.0          100.0
11          86.0           91.0
12          86.0           86.0
13          96.0           72.0
14          96.0           93.0
15          98.0           83.0
16          96.0           98.0
17          90.0           96.0
18          90.0           91.0
19          94.0          100.0

In [58]:
def func(x):
    if x["ЕГЭ...рус.яз."] > x["ЕГЭ...матем."]:
        return 'Да'
    else:
        return 'Нет'

data['Новый столбец'] = data.apply(func, axis=1)

data

,Пол,Сумма.баллов,ЕГЭ...матем.,ЕГЭ...рус.яз.,Аттестат.с.отличием.оценка,ГТО.оценка,Сочинение.оценка,Регион,Тип.насел..пункта,Дата.рождения,День.рождения,Месяц.рождения,Название,Новый столбец
0,МУЖСКОЙ,388,90.0,98.0,5,0,1,Красноярский край,ГОРОД,24.09.1998,24,9,Да,Да
1,ЖЕНСКИЙ,351,84.0,87.0,0,0,2,Чувашская Респ,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,14.02.1997,14,2,Да,Да
2,ЖЕНСКИЙ,355,94.0,91.0,5,0,2,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,25.03.2000,25,3,Нет,Нет
3,ЖЕНСКИЙ,338,76.0,88.0,5,0,2,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,19.11.1999,19,11,Да,Да
4,МУЖСКОЙ,349,82.0,93.0,5,0,2,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,12.12.1999,12,12,Да,Да
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1385,МУЖСКОЙ,396,100.0,98.0,0,0,2,Челябинская обл,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,17.07.1999,17,7,Нет,Нет
1386,ЖЕНСКИЙ,291,92.0,93.0,5,0,2,Хабаровский край,ГОРОД,27.07.1999,27,7,Да,Да
1387,МУЖСКОЙ,397,100.0,93.0,5,0,1,Дагестан Респ,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,30.08.1999,30,8,Нет,Нет
1388,ЖЕНСКИЙ,325,76.0,98.0,5,2,2,Свердловская обл,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,17.11.1999,17,11,Да,Да
1389,МУЖСКОЙ,404,100.0,96.0,5,0,3,Челябинская обл,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,28.02.2000,28,2,Нет,Нет

In [79]:
ndata = data[(data['ЕГЭ...матем.'] + data['ЕГЭ...рус.яз.']) > 190]
ndata

,Пол,Сумма.баллов,ЕГЭ...матем.,ЕГЭ...рус.яз.,Аттестат.с.отличием.оценка,ГТО.оценка,Сочинение.оценка,Регион,Тип.насел..пункта,Дата.рождения,День.рождения,Месяц.рождения
10,ЖЕНСКИЙ,399,96.0,100.0,5,0,2,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,13.11.1999,13,11
16,МУЖСКОЙ,388,96.0,98.0,0,0,0,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,15.02.2000,15,2
19,ЖЕНСКИЙ,364,94.0,100.0,5,0,3,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,10.04.1999,10,4
20,МУЖСКОЙ,375,100.0,93.0,5,0,2,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,05.08.1999,5,8
37,МУЖСКОЙ,393,100.0,96.0,0,0,1,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,15.02.2000,15,2
...,...,...,...,...,...,...,...,...,...,...,...,...
1355,ЖЕНСКИЙ,403,96.0,100.0,5,0,2,Башкортостан Респ,НАСЕЛЕННЫЙ ПУНКТ СЕЛЬСКОГО ТИПА,13.06.1999,13,6
1370,ЖЕНСКИЙ,396,98.0,93.0,5,0,2,Чувашская Респ,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,28.06.1999,28,6
1385,МУЖСКОЙ,396,100.0,98.0,0,0,2,Челябинская обл,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,17.07.1999,17,7
1387,МУЖСКОЙ,397,100.0,93.0,5,0,1,Дагестан Респ,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,30.08.1999,30,8
1389,МУЖСКОЙ,404,100.0,96.0,5,0,3,Челябинская обл,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,28.02.2000,28,2

3. Добавим группировку (groupby) и агрегирующие функции (agg) в Python или аналогичные функции
пакета dplyr в R:
    1. вывести средние баллы девочек и мальчиков
    2. вывести средние баллы, имеющих аттестат с отличием и нет,
    3. вывести средние баллы по 4 категориям, получающимся при сочетании двух предыдущих пунктов,
    4. найти число студентов с баллом ЕГЭ по математике, лежащим в заданном диапазоне,
    5. создать датасет с количествами студентов, баллы которых лежат в заданных диапазонах (<70,
    70-80 и т.д.).

In [89]:
print("Средние баллы девочек и мальчиков: ")
data.iloc [:, [0,1]].groupby('Пол').mean()

Средние баллы девочек и мальчиков:

         Сумма.баллов
Пол
ЖЕНСКИЙ    332.620172
МУЖСКОЙ    331.137446

In [93]:
print("По аттестату: ")
data.iloc [:, [1, 4]].groupby('Аттестат.с.отличием.оценка').mean()

По аттестату:

                            Сумма.баллов
Аттестат.с.отличием.оценка
0                             325.807783
5                             340.750923

In [94]:
print("По обоим вышеперечисленным параметрам: ")
data.iloc[:, [0, 1, 4]].groupby(['Аттестат.с.отличием.оценка', 'Пол']).mean()

По обоим вышеперечисленным параметрам:

                                    Сумма.баллов
Аттестат.с.отличием.оценка Пол
0                          ЖЕНСКИЙ    325.145631
                           МУЖСКОЙ    326.020249
5                          ЖЕНСКИЙ    338.542308
                           МУЖСКОЙ    342.787234

In [6]:
print("Введите границы диапазона: ")
a = int(input())
b = int(input())

ndata = data[(data['ЕГЭ...матем.'] < b) & (data['ЕГЭ...матем.'] > a)]
print(ndata.shape[0])

ndata

Введите границы диапазона:

 56
 89

903

,Пол,Сумма.баллов,ЕГЭ...матем.,ЕГЭ...рус.яз.,Аттестат.с.отличием.оценка,ГТО.оценка,Сочинение.оценка,Регион,Тип.насел..пункта,Дата.рождения,День.рождения,Месяц.рождения
1,ЖЕНСКИЙ,351,84.0,87.0,0,0,2,Чувашская Респ,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,14.02.1997,14,2
3,ЖЕНСКИЙ,338,76.0,88.0,5,0,2,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,19.11.1999,19,11
4,МУЖСКОЙ,349,82.0,93.0,5,0,2,Москва г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,12.12.1999,12,12
7,ЖЕНСКИЙ,364,80.0,86.0,0,0,2,Санкт-Петербург г,ГОРОД ФЕДЕРАЛЬНОГО ЗНАЧЕНИЯ,22.12.1998,22,12
8,МУЖСКОЙ,368,84.0,93.0,0,0,2,Владимирская обл,ГОРОД,13.06.1999,13,6
...,...,...,...,...,...,...,...,...,...,...,...,...
1380,МУЖСКОЙ,319,81.0,82.0,0,0,2,Башкортостан Респ,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,01.05.1995,1,5
1382,МУЖСКОЙ,336,88.0,66.0,0,0,0,Пермский край,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,06.09.1999,6,9
1383,ЖЕНСКИЙ,336,86.0,93.0,0,0,0,Пермский край,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,03.02.1998,3,2
1384,МУЖСКОЙ,313,78.0,65.0,0,0,1,Ростовская обл,ГОРОД,24.12.1998,24,12
1388,ЖЕНСКИЙ,325,76.0,98.0,5,2,2,Свердловская обл,ЦЕНТР СУБЪЕКТА ФЕДЕРАЦИИ,17.11.1999,17,11